[package]
name = "souper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
downcast-rs = "1.2.0"
num-derive = "0.4.0"
num-traits = "0.2.16"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.49"
